env:
  browser: true
  node: true
  es6: true

plugins:
  - babel

extends:
  - eslint:recommended
  - llama
  - prettier

parserOptions:
  sourceType: module

parser: babel-eslint

rules:
  require-jsdoc: off
